OPTIONS (SKIP=1)
LOAD DATA
INFILE cpt4_to_snomed_condition_map.txt
INTO TABLE cpt4_to_snomed_condition_map
REPLACE
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
SOURCE_CODE,  
SOURCE_VOCABULARY_ID,
SOURCE_CODE_DESCRIPTION,
TARGET_CONCEPT_ID,
TARGET_VOCABULARY_ID,
MAPPING_TYPE,
PRIMARY_MAP NULLIF PRIMARY_MAP='NULL'
)
