OPTIONS (SKIP=1)
LOAD DATA
INFILE hcpcs_to_snomed_condition_map.txt
INTO TABLE hcpcs_to_snomed_condition_map
REPLACE
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
SOURCE_CODE,  
SOURCE_VOCABULARY_ID,
SOURCE_CODE_DESCRIPTION CHAR(1000) "SUBSTR(:SOURCE_CODE_DESCRIPTION,1,255)",
TARGET_CONCEPT_CODE,
TARGET_VOCABULARY_ID,
MAPPING_TYPE,
PRIMARY_MAP NULLIF PRIMARY_MAP='NULL'
)
