OPTIONS (SKIP=1)
LOAD DATA
INFILE hcpcs.txt
INTO TABLE hcpcs
REPLACE
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
SOURCE_CODE,  
SOURCE_CODE_DESCRIPTION CHAR(1000) "SUBSTR(:SOURCE_CODE_DESCRIPTION,1,255)",
LEN
)
