LOAD DATA
INFILE icd9_to_concept_map.txt
INTO TABLE icd9_to_concept_map
REPLACE
FIELDS TERMINATED BY '\t'
TRAILING NULLCOLS
(
SOURCE_CODE,  
SOURCE_VOCABULARY_ID,
SOURCE_CODE_DESCRIPTION,
TARGET_CONCEPT_ID,
TARGET_VOCABULARY_ID,
MAPPING_TYPE,
PRIMARY_MAP NULLIF PRIMARY_MAP='NULL',
VALID_START_DATE DATE "YYYY-MM-DD",
VALID_END_DATE DATE "YYYY-MM-DD",
INVALID_REASON NULLIF INVALID_REASON='NULL'
)
